### ISSUE TITLE
Niekonsystencja Świdnica 28-03-2020

### ISSUE THREAD

**Issue by not7cd** [dtandev/coronavirus#7]
https://github.com/dtandev/coronavirus/blob/master/data/CoronavirusPL%20-%20Timeseries.csv#L1234-L1235

Nie ma Świdnicy w woj. Zachodniopomorskim

Najbliższe źródło https://swidnica24.pl/2020/03/17-ofiara-koronawirusa-w-polsce-najnowsze-dane-dla-powiatu-swidnickiego/
Pytanie czy to nie są wyniki dla Szczecina

**Comment by dtandev** [comment]
> https://github.com/dtandev/coronavirus/blob/master/data/CoronavirusPL%20-%20Timeseries.csv#L1234-L1235
> 
> Nie ma Świdnicy w woj. Zachodniopomorskim
> 
> Najbliższe źródło https://swidnica24.pl/2020/03/17-ofiara-koronawirusa-w-polsce-najnowsze-dane-dla-powiatu-swidnickiego/
> Pytanie czy to nie są wyniki dla Szczecina

Zgłoszone. Weryfikujemy wpisy. Dzięki.

**Comment by dtandev** [comment]
Wszystkie Twoje Fix też na bieżąco uwzględniam w bazie, więc jutrzejszy update powinien być wolny od literówek

**Comment by dtandev** [comment]
> Pytanie czy to nie są wyniki dla Szczecina

Chodziło o Świdwin. 2 przypadki z powiatu świdwińskiego. Jutro update.
